version: '3'
services:
  client:
    build:
      context: .
      dockerfile: Dockerfile-client
    depends_on:
      - load_balancer
    networks:
      - my_network

  server1:
    build:
      context: .
      dockerfile: Dockerfile-server
    networks:
      - my_network

  server2:
    build:
      context: .
      dockerfile: Dockerfile-server
    networks:
      - my_network

  load_balancer:
    build:
      context: .
      dockerfile: Dockerfile-load-balancer
    ports:
      - "80:80"
    networks:
      - my_network

networks:
  my_network:
