version: '3.8'
services:
  load_balancer:
    build: ./load_balancer
    ports:
      - "80:80"
    deploy:
      replicas: 1

  client:
    build: ./client
    deploy:
      replicas: 5

  server:
    build: ./server
    deploy:
      replicas: 3
