version: "3"

services:
  client:
    build: ./client

  server1:
    build: ./server
    ports:
      - "8001:8000"

  server2:
    build: ./server
    ports:
      - "8002:8000"

  server3:
    build: ./server
    ports:
      - "8003:8000"

  load_balancer:
    build: ./load_balancer
    ports:
      - "80:80"
